linters:
  enable-all: true
  disable:
    - wsl
    - dupword
    - depguard
    - godox
    - wrapcheck
    - varnamelen
    - ireturn
    - gochecknoglobals
    - exhaustruct
linters-settings:
  goconst:
    ignore-tests: true
    min-len: 5
  revive:
    rules:
      - name: unused-parameter
        disabled: true
  interfacebloat:
    max: 11
issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - depguard
        - scopelint
        - testpackage
        - paralleltest