linters:
  enable-all: true
  disable:
    - wsl
    - dupword
    - depguard
    - godox
    - wrapcheck
    - varnamelen
    - ireturn
    - gochecknoglobals
    - exhaustruct
    - ifshort # deprecated (since v1.48.0) due to: The repository of the linter has been deprecated by the owner.
    - interfacer # deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.
    - deadcode # deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused.
    - nosnakecase # is deprecated (since v1.48.1) due to: The repository of the linter has been deprecated by the owner. Replaced by revive(var-naming).
    - varcheck # is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused.
    - maligned # is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner. Replaced by govet 'fieldalignment'.
    - scopelint # is deprecated (since v1.39.0) due to: The repository of the linter has been deprecated by the owner. Replaced by exportloopref.
    - exhaustivestruct # is deprecated (since v1.46.0) due to: The owner seems to have abandoned the linter. Replaced by exhaustruct.
    - golint # is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner. Replaced by revive.
    - structcheck # is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused.
linters-settings:
  goconst:
    ignore-tests: true
    min-len: 5
  revive:
    rules:
      - name: unused-parameter
        disabled: true
issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - depguard
        - scopelint
        - testpackage
        - paralleltest